### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by chriseverson** [jonsuh/hamburgers#1]
@jonsuh: It would be awesome if Hamburgers supported installation via Bower. If you're open to that idea, I can send a pull request your direction with the necessary updates.

**Comment by jonsuh** [comment]
Hey @chriseverson, that was something on my list. Just pushed a commit for it that resolves it https://github.com/jonsuh/hamburgers/commit/4ef3c5a453206a4e1549e1f18a8ef83e80f72914

Only issue us a package named `hamburgers` was already registered :( so it’s `bower install css-hamburgers`
