### ISSUE TITLE
It comes back to the second state when reloading page

### ISSUE THREAD

**Issue by chaveamin** [jonsuh/hamburgers#101]
![2021-03-16_19-44-35](https://user-images.githubusercontent.com/78597787/111344218-6d79a280-8691-11eb-903c-14131b1f233c.gif)

**Comment by fedepasqui** [comment]
did you find a solution for this?

**Comment by jonsuh** [comment]
Clicking adds the `is-active` class but refreshing will restore the HTML to its original state, which is without the `is-active` class.

You will have to find a dynamic solution that remembers the last state and restores on refresh. This library does not and is not designed to provide that solution.
