### ISSUE TITLE
Adding classes to provide different sizes

### ISSUE THREAD

**Issue by MoradHamdy** [jonsuh/hamburgers#13]
Hi there,

I like how this stuff made hamburger icons easy to handle! Thank you for your effort.

It would be great if there are classes to be used to control size, for example like adding class large, medium or small to give different sizes look. Or some another method to control hamburger icons size.

**Comment by aleksandrmaksimoviclt** [comment]
@MoradHamdy Hey buddy, do the following:

- Open **_dist/hamburgers.css_** 
- Find line with `.hamburger-inner, .hamburger-inner::before, .hamburger-inner::after{} ` classes
- Change `height:40px;` value to needed size.

**Comment by tomholford** [comment]
+1, this would be nice to have for responsive layouts

**Comment by jonsuh** [comment]
As @aleksandrmaksimoviclt suggested, I would advise for customizing the sizing in the `CSS` file or ideally if you import the `SCSS` version you could change the variables for the sizing, which is in the documentation.
