### ISSUE TITLE
Currently the hamburger menu will not animate when clicked

### ISSUE THREAD

**Issue by adrhumphreys** [jonsuh/hamburgers#14]
Not sure why it is behaving that way

No code changed in the sass files and this is what i have on my page

```
<button class="hamburger hamburger--emphatic" type="button">
  <span class="hamburger-box">
    <span class="hamburger-inner"></span>
  </span>
  <br />
  <span class="hamburger-label">Menu</span>
</button>
```

**Comment by jonsuh** [comment]
@adrhumphreys Hey, you would need to integrate the appropriate JavaScript to incorporate the click behavior—it should dynamically add or remove the `is-active` CSS class that handles the animation. This is explained in [#4 of the Usage section of the Readme](https://github.com/jonsuh/hamburgers/blob/master/README.md#usage):

> Trigger the active state by appending class name `is-active`:
> ```html
<button class="hamburger hamburger--collapse is-active" type="button">
  <span class="hamburger-box">
    <span class="hamburger-inner"></span>
  </span>
</button>
```
> Since the class name would have to be toggled via JavaScript and implementation would differ based on the context of how you plan on using the hamburger, I’m going to leave the rest up to you.

Here’s are a couple of hints on how you can incorporate it:

Here’s a snippet of how to toggle a class name on click with JavaScript:

```js
<script>
  // Look for .hamburger
  var hamburger = document.querySelector(".hamburger");
  // On click
  hamburger.addEventListener("click", function() {
    // Toggle class "is-active"
    hamburger.classList.toggle("is-active");
    // Do something else, like open/close menu
  });
</script>
```
...or jQuery:

```js
<script>
  var $hamburger = $(".hamburger");
  $hamburger.on("click", function(e) {
    $hamburger.toggleClass("is-active");
    // Do something else, like open/close menu
  });
</script>
```

Hope this helps
