### ISSUE TITLE
Add setting for active state

### ISSUE THREAD

**Issue by terryupton** [jonsuh/hamburgers#18]
It would be great to add a setting to control the active state of the icon. So we can change the colour of the cross etc. 
Lovely work though. Thanks.

**Comment by priyankmaniar** [comment]
I'm looking for the same functionality. I want to change the color of the X icon to be different than the hamburger icon.

**Comment by andreamaiolo** [comment]
Check this PR #20

**Comment by priyankmaniar** [comment]
Thanks so much! :) I'll give it a try.

**Comment by terryupton** [comment]
@jonsuh - will you be merging this PR at all?

**Comment by terryupton** [comment]
@jonsuh - will you be merging this PR #20 at all?
