### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by andreamaiolo** [jonsuh/hamburgers#19]
Hi,
I've spotted an issue while using this library with Firefox. Once the transition is complete, the icon (after some milliseconds) lose its thickness. Am I the only one that is experiencing this problem?

**Comment by stratboy** [comment]
Me too, latest firefox, osx el capitan. Still, for me it's not an issue since the button is going to be used only on mobile devices.

**Comment by monolux** [comment]
On SO someone also reports this issue, though not with these particular "hamburgers".
Seems to be a Firefox issue.
[Why is there a strange “thinning” effect visible on these span tags after the transition has finsihed?](https://stackoverflow.com/questions/40708997/why-is-there-a-strange-thinning-effect-visible-on-these-span-tags-after-the-tr)

**Comment by andreamaiolo** [comment]
Since this is not related to this library, I'm going to close the issue. Thanks for the SO link
