### ISSUE TITLE
Make hamburger stationary when toggled

### ISSUE THREAD

**Issue by F-Tahir** [jonsuh/hamburgers#22]
Hi.

I love this plugin but I'm trying to edit the css such that when the hamburger is clicked, the positioning doesn't change such that the X is underneath the toggled menubar. Is this possible? If so, what do I need to change in the css? I'm using 3DX transition. Any help is appreciated.

Also, there is an outline on the hamburger after I click it. Is there any way to remove that outline?

**Comment by jonsuh** [comment]
Without additional context, not sure if I can help with the positioning.

Remove the outline with `.hamburger { outline: 0 }`.
