### ISSUE TITLE
js needed

### ISSUE THREAD

**Issue by stratboy** [jonsuh/hamburgers#27]
Hi, I think you should mention on your documentation that one should add the hamburgers.js file or add a click mouse event that toggles an is-active class on the button?

**Comment by FeBe95** [comment]
It is mentioned:

> Since the class name would have to be toggled via JavaScript and implementation would differ based on the context of how you plan on using the hamburger, I’m going to leave the rest up to you.

Just use something like this (jQuery):
```
$(document).ready(function(){
  $('.hamburger').click(function(){
    $(this).toggleClass('is-active');
  });
});
```

**Comment by jonsuh** [comment]
@stratboy Since I can’t guess how you’re going to implement the hamburger menu, I decided not to try and guess the JavaScript. If you’re looking for a working example, look at `dist/example.html` https://github.com/jonsuh/hamburgers/blob/master/dist/example.html#L179
