### ISSUE TITLE
"Spin Reverse" wrong calculation

### ISSUE THREAD

**Issue by FeBe95** [jonsuh/hamburgers#28]
`.hamburger--spin-r.is-active .hamburger-inner::after` for "spin reverse" needs to be rotated 90deg instead of -90deg like the normal spin (line 36 in spin-r.scss)

**Comment by jonsuh** [comment]
Hey @FeBe95. Thanks for pointing that out!

I pushed a commit to fix it https://github.com/jonsuh/hamburgers/commit/61e9242da3d42ef751e047ca8f72d672c25267f4 and updated with a new release to include the fix https://github.com/jonsuh/hamburgers/releases/tag/v0.6.0.
