### ISSUE TITLE
Recommendation: Relative units

### ISSUE THREAD

**Issue by tomlutzenberger** [jonsuh/hamburgers#29]
Instead of using fixed pixel units, it would add a lot more flexibility using `em`.
I already did it on a project and could create a PR.

**Comment by jonsuh** [comment]
@tomlutzenberger this library is totally capable of handling `ems` and shouldn’t break, so nothing is stopping one from changing them around. For the library defaults, though, I left it as `px` since, in general, they are more predictable and more accurate with small values.
