### ISSUE TITLE
Issue animating the burger menu

### ISSUE THREAD

**Issue by fcogutierrez** [jonsuh/hamburgers#30]
I am animating a burger menu changing the `margin` and `width` of two divs, and in the meantime, a ***burger icon*** it is animated switching the class `is-active`.

The result, as you can see, is a jumpy effect in the content of the burger menu (***green*** area):
http://www.codeply.com/go/7xjGnw5yEc

Executing the burger button: you can see that, for some miliseconds, the **_green_** area dissapears.
Executing the toggle button: you can see that there are no jumps.

I only reproduce it in Google Chrome.

What is it happening? How can I fix this strange behaviour?

**Comment by jonsuh** [comment]
@fcogutierrez I took a look and the animation you’re pointing out is unrelated to the hamburger icon animation itself.

Though I can’t fully debug for you, I would suggest separate elements for `burger-wrapper` and `content`. Good luck
