### ISSUE TITLE
Color change on hover

### ISSUE THREAD

**Issue by nathanharper** [jonsuh/hamburgers#31]
I'm trying to make the hamburger change color on hover, but it's obviously coming into conflict with some CSS, and as a result the patty and buns are changing color at a different rate. Is there any good workaround to this?

**Comment by Ericky14** [comment]
Include this in your scss file.

```
.hamburger-inner {
    &, &::before, &::after {
        background-color: #FFF;
    }
}
```

**Comment by nicolasbinet** [comment]
you have to homogenize the background transition property

    .hamburger-inner {
        &,
        &::before,
        &::after {
            @include transition(background 0s linear);
        }
    }

**Comment by fatmarker** [comment]
I don't use SASS. Can you explain in normal CSS please?

**Comment by glodov** [comment]
@fatmarker you would better use SASS.

In normal CSS above SASS means:
```
.hamburger-inner, .hamburger-inner::before, .hamburger-inner::after {
  transition: background 0s linear;
}
```
