### ISSUE TITLE
Less version?

### ISSUE THREAD

**Issue by n8-sd** [jonsuh/hamburgers#32]
Any plans for a .less version?

**Comment by jonsuh** [comment]
@n8-sd I’ll look into this and see how feasible it would be. To my understanding, some of things I’m relying on with `SCSS` can’t be done with `LESS`; therefore, it would have to be refactored or accomplished differently to work in a LESS environment.

**Comment by jonsuh** [comment]
Decided this isn’t something worth pursuing, so closing the issue. Happy to revisit if someone opens a PR with LESS support.
