### ISSUE TITLE
change active class to 'active'

### ISSUE THREAD

**Issue by stratboy** [jonsuh/hamburgers#41]
Hi! It would be great if you changed the active class to 'active' instead of is-active, since the dashed version can sometimes lead to some problems.

I know we can just mod the scss files, yes, no prob, but then updates would be broken (and again, yes, it would be simple to fix it up as well, but it would be simpler to keep things simple :)).

Thanks for your great code, Regards

**Comment by jonsuh** [comment]
@stratboy I appreciate the suggestion; however, I believe the use of `is-active` is better practice. The `is-*` prefix is used to define selectors that are specifically for altering the state of a component.

That said, a dash in a CSS name should not lead to any problems—it is extremely common practice in CSS.
