### ISSUE TITLE
Annoying blue - selection lines

### ISSUE THREAD

**Issue by ghost** [jonsuh/hamburgers#42]
Hey there, 

I'm struggling to remove the annoying line next to the hamburger button.. It shows in Chrome and Safari as well and I have no idea why. 

Here is what I'm talking about:

![screen shot 2017-07-22 at 09 50 35](https://user-images.githubusercontent.com/24611781/28489791-96a3d8cc-6ec3-11e7-8f0d-e47b03cb8c57.jpg)
![screen shot 2017-07-22 at 09 50 46](https://user-images.githubusercontent.com/24611781/28489795-a2166530-6ec3-11e7-9ab1-23c643f07ff0.jpg)

Also, when I'm resizing the layers and the spacing for example. They get messed up, the spacing between them is going to be different and the height of (usually just the top) the layer gets smaller than the others.

Any idea on how, to remove them?

**Comment by GrayOwl90** [comment]
Hey, perhaps you should try to change default settings (found in _sass/hamburgers/hamburgers.scss); $hamburger-padding-x : 15px;$hamburger-padding-y : 15px;$hamburger-layer-width : 40px;$hamburger-layer-height : 4px;$hamburger-layer-spacing : 6px;$hamburger-layer-color : #000;$hamburger-layer-border-radius : 4px;$hamburger-hover-opacity : 0.7;$hamburger-hover-transition-duration : 0.15 s;$hamburger-hover-transition-timing-function: linear; But it's not for sure, I never faced such a problem.22.07.2017, 15:55, "David Dragovacz" <notifications@github.com>:Hey there,
I'm struggling to remove the annoying line next to the hamburger button.. It shows in Chrome and Safari as well and I have no idea why.
Here is what I'm talking about:


Also, when I'm resizing the layers and the spacing for example. They get messed up, the spacing between them is going to be different and the height of (usually just the top) the layer gets smaller than the others.
Any idea on how, to remove them?

**Comment by kevinmwangi** [comment]
Hey @dragidavid, Add `&:focus {outline:0;}` after `&:hover` on line 29 in _base.scss then compile to css.
