### ISSUE TITLE
Pure CSS support

### ISSUE THREAD

**Issue by Eseperio** [jonsuh/hamburgers#44]
It could be good if pure css support is available.
When using purecss you do this:
Html:
`checkbox`
`label`
CSS:
```
input[type="checkbox"] {
display: none;
}
input[type="checkbox"]:checked + label {
 //alternate css rules for label (the same as .is_active)
}
```

PureCSS is a common practice in well developed websites.

**Comment by Eseperio** [comment]
Adding (in sass) `input[type="checkbox"]:checked + label &` after .is-active is enough to enable compatibility with pure css. Take care of the last ampersand.
```
&.is-active, input[type="checkbox"]:checked + label & {
      .hamburger-inner {
        $y-offset: $hamburger-layer-spacing + $hamburger-layer-height;

        transform: translate3d(0, $y-offset, 0) rotate(45deg);

        &::before {
          transform: rotate(-45deg) translate3d($hamburger-layer-width / -7, $hamburger-layer-spacing * -1, 0);
          opacity: 0;
        }

        &::after {
          transform: translate3d(0, $y-offset * -2, 0) rotate(-90deg);
        }
      }
    }
```

**Comment by jonsuh** [comment]
Thank you for the suggestion!

I like and generally use CSS hacks (like this); however, for the sake of accessibility, I would prefer to avoid it. The `:checked` selector is [not supported on some mobile platforms](http://quirksmode.org/css/selectors/mobile.html#t60), therefore is not a11y friendly.

I appreciate the time you took to provide code examples and would come in handy for anyone else that wants to implement this solution on their own.

**Comment by Eseperio** [comment]
The list you provided is 4 years old. Currently all the browsers support :checked [caniuse.com-:checked](http://caniuse.com/#search=%3Achecked).

Retro compatibility is a very bad practice, because encourages people to have obsolete and unsecure software.

**Comment by leocaseiro** [comment]
I agree. You should reconsider it.

This is a nice way to make a custom checkbox accessible.

Here is my codepen using hamburguer squeeze: https://codepen.io/leocaseiro/pen/WNbqBbo
