### ISSUE TITLE
Swap @if burguers statement into a @mixins

### ISSUE THREAD

**Issue by HectorLS** [jonsuh/hamburgers#47]
Hello, nice burguers 👍 🍔  !

Usually each project has just one burguer.
And of course we can go into the files and comment the @import, but this means touching files in node_modules ( that problably will rely on a problem if we try a package version update ) 😢 .

Wouldn't be a better approach just have `@mixins` for each burguer ( and have them listed in the DOC) so i can `@include` just the one that i want ? 

Keeping your files clean 😃.

**Comment by jonsuh** [comment]
@HectorLS Hey Hector, thanks!

This was designed in a way that you won’t have to mess with anything in `node_modules` and also include just the ones you want.

In the [Customization section](https://github.com/jonsuh/hamburgers#customization) of the `README.md` there are instructions on how to do so.

In short, you basically take the `$hamburger-types` map, remove all the ones you don’t want and just leave the ones that you want included. For example, if you only want the `squeeze` variant, you would put the following in your settings file or one of your `.scss` files for your project:

```
$hamburgers-types: (
  squeeze
);
```

When the CSS is compiled, only that type will be included.

Hope that helps.
