### ISSUE TITLE
Best way define custom hover over transistion

### ISSUE THREAD

**Issue by beourmuse** [jonsuh/hamburgers#50]
Go from this

<img width="53" alt="screen shot 2017-11-21 at 4 24 00 pm" src="https://user-images.githubusercontent.com/7823614/33053522-dead0a2e-ced8-11e7-82b0-8a8949ed2ab7.png">

to this:

<img width="46" alt="screen shot 2017-11-21 at 4 28 51 pm" src="https://user-images.githubusercontent.com/7823614/33053562-170b0588-ced9-11e7-9c82-d7c903d381cb.png">

Can this be done with the $hamburger-hover-filter parameter somehow, or is javascript needed?

**Comment by jonsuh** [comment]
@beourmuse With the example from this issue https://github.com/jonsuh/hamburgers/issues/49 you would reset each layer with `width: $hamburger-layer-width;`

You’d then have to modify the `transition-property` so it also transitions the `width`

Frankly I’m not sure if this library is the ideal one for what you’re trying to accomplish. It isn’t impossible, but requires a lot of customization outside of the scope of what this library is designed to do.
