### ISSUE TITLE
Compatibility with Bootstrap 4 issue

### ISSUE THREAD

**Issue by Tes3awy** [jonsuh/hamburgers#54]
I am trying to use your hamburgers instead of Bootstrap's default one. I changed this part o fthe code 
```
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
```
to be

```
<button class="hamburger hamburger--slider" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="hamburger-box">
        <span class="hamburger-inner"></span>
    </span>
</button>
```

The hamburger icon is present, however, the animation is not working for some reason that I don't understand. Do you have any idea why isn't it working?

**Comment by glodov** [comment]
Hello, @Tes3awy.
There is a style attached to `.hamburger--slider.is-active` so animation is triggered when `.is-active` class is present on button. I've done it with jQuery:

```javascript
    $('.navbar-toggler').on('click', function () {
      $(this).toggleClass('is-active');
      $('.navbar-collapse.show[id]').each(function () {
        $('.navbar-toggler.is-active[data-target="#' + $(this).attr('id') + '"]').click();
      });
    });
```

**Comment by Tes3awy** [comment]
Thanks a lot for taking the issue into consideration 😄. Are you going to add Bootstrap 4 support directly to the CSS file soon?

**Comment by cfxd** [comment]
This is doable without JavaScript. Just setup the Bootstrap navbar markup, then add the Hamburgers markup, then in your SCSS:

```scss
.navbar-toggler.hamburger[aria-expanded=true] {
  @extend .is-active;
}
```

**Comment by eberkund** [comment]
Unfortunately Bootstrap applies the class at the end of the animation where the menu slides down which makes the hamburger animations out of sync. Did anyone else encounter this and find an easy solution?

**Comment by cfxd** [comment]
My solution works regardless of when the class is applied because it doesn't rely on the class; it relies on the attribute

**Comment by eberkund** [comment]
> My solution works regardless of when the class is applied because it doesn't rely on the class; it relies on the attribute

Yea your solution works, but the aria attribute only changes once the bootstrap animation finishes (the one where the menu slides open).
