### ISSUE TITLE
Weird blue background on click

### ISSUE THREAD

**Issue by Nirco96** [jonsuh/hamburgers#56]
Hey, i'm using the spin hamburger button, but I get a weird blue transparent overlay when i'm clicking the button. How do I get rid of it using just CSS? 
It looks like this (hamburger being long-clicked):
https://i.gyazo.com/430dc0065c62d9c52f24fb1a1ba99adf.png

**Comment by jonsuh** [comment]
@Nirco96 By default the hamburgers library sets `background-color: transparent` https://github.com/jonsuh/hamburgers/blob/master/_sass/hamburgers/_base.scss#L16; therefore, I can only guess it’s code elsewhere in your codebase that’s affecting the appearance of the button.

I would inspect the button using the development tools of your browser of choice and try to determine what’s causing it.
