### ISSUE TITLE
Doesn't work! :(

### ISSUE THREAD

**Issue by Steve2428** [jonsuh/hamburgers#57]
So I have the css and it linked in <head> I have put the code in the <body> and absolutely nothing happens? I click and get nothing.
<img width="657" alt="screen shot 2018-04-18 at 15 03 21" src="https://user-images.githubusercontent.com/38500089/38936898-be6f2bba-4319-11e8-8fd0-ea0eb655447e.png">

**Comment by jonsuh** [comment]
@Steve2428 As noted by @andreamaiolo, you also have to have JavaScript to toggle the active/inactive states. FWIW it’s stated in point #4 in [Usage](https://github.com/jonsuh/hamburgers#usage) of the [README](https://github.com/jonsuh/hamburgers/blob/master/README.md).

The included snippet should work, but is not the only answer. There are many different ways to get it to work.
