### ISSUE TITLE
Size of icon

### ISSUE THREAD

**Issue by TngSam** [jonsuh/hamburgers#62]
Hello there!
How can I adequately change the size of icon?

**Comment by jonsuh** [comment]
You can adjust the width, height and spacing via the `$hamburger-layer-width`, `$hamburger-layer-height`, and `$hamburger-layer-spacing` variables. Please review the [Customization section of the README](https://github.com/jonsuh/hamburgers#customization).

**Comment by marcus-at-localhorst** [comment]
The best way to change the size of the hamburger is to use `transform`. Keeps everything in place.

```css
.hamburger{
  transform: scale(.5);
}
```

**Comment by DanailMinchev** [comment]
The answer of @marcus-at-localhost should be added to official docs! Thank you @marcus-at-localhost !
