### ISSUE TITLE
Close on click

### ISSUE THREAD

**Issue by dumitru** [jonsuh/hamburgers#64]
How to close hamburger on click?

In my case is needed because it is used in one page site.

**Comment by jonsuh** [comment]
@dumitru Do you mind clarifying what you mean by close? The hamburgers only have an `inactive` and `active` state...

**Comment by jonsuh** [comment]
Add the class `is-active` to put it into the active state, and remove `is-active` to return it back to the normal state.

You will need to use JavaScript and event handlers to add/remove this class on click/tap. You can look at https://github.com/jonsuh/hamburgers/issues/27 for examples. And be sure to read the https://github.com/jonsuh/hamburgers/blob/master/README.md for documentation and more details on how this works.
