### ISSUE TITLE
Package deprecated on npm

### ISSUE THREAD

**Issue by OscarBarrett** [jonsuh/hamburgers#67]
Was this a mistake? Message says `@v1.0.0` (which has been removed) but it seems like the whole package is deprecated.

![screen capture on 2018-10-05 at 11-32-46 1](https://user-images.githubusercontent.com/3511332/46514796-a7280b80-c892-11e8-8ade-6605aacddde1.gif)

**Comment by jonsuh** [comment]
@OscarBarrett Thank you for bringing this to my attention—this was not intentional! I’ll look into it tonight and can report back

**Comment by jonsuh** [comment]
@OscarBarrett I think this has been resolved—would you mind double checking for me?

**Comment by OscarBarrett** [comment]
Yeah looking good now, thanks!
