### ISSUE TITLE
How to make lines of hamburger thinner?

### ISSUE THREAD

**Issue by pkiula** [jonsuh/hamburgers#78]
Hello, love this script. Thanks for making this available! 

Question: how can we make the lines of the hamburger and the "X" close button thinner? 

Many thanks!

**Comment by Zemke** [comment]
If you’re using SASS `$hamburger-layer-height` is your way to go. 

If you’re using plain CSS the selector would be `.hamburger-inner, .hamburger-inner::before, .hamburger-inner::after` and modify its `height`.

**Comment by pkiula** [comment]
Thank you Zemke. What a lovely plugin. Huge fan.
