### ISSUE TITLE
how do i change the color of the hamburger lines????

### ISSUE THREAD

**Issue by sanidhya711** [jonsuh/hamburgers#97]
how do i change the color of the hamburger lines????

**Comment by achscholar** [comment]
Modify the two background-color values located in the CSS file you included, which is probably dist/hamburger.css. One is for the hamburger lines and the other is for the color of the X after the animation finishes.

**Comment by kenxdrgn** [comment]
You could also declare the css as below to change the color.
```
.hamburger.is-active .hamburger-inner,
.hamburger.is-active .hamburger-inner::before,
.hamburger.is-active .hamburger-inner::after {
  background-color: red;
}
.hamburger-inner,
.hamburger-inner::before,
.hamburger-inner::after {
  background-color: red;
}
```
